### ISSUE TITLE
ModuleNotFoundError: No module named 'models.VAE'

### ISSUE THREAD

**Issue by Bobby-youngking** [idiap/potr#1]
sorry, where is the VAE?

**Comment by legan78** [comment]
Thanks for your comment. It was an old unused module. We have removed it.

**Comment by Bobby-youngking** [comment]
so the code is a new version now???

**Comment by legan78** [comment]
The code is the same version as the one used for publishing our paper. In our experiments we did not report results with variational auto-encoder.
