### ISSUE TITLE
NTURGBD with these txt.files?

### ISSUE THREAD

**Issue by ztb-35** [idiap/potr#11]
Sorry, what is the 'action_labels.txt', 'training_files.txt', ' testing_files.txt', and 'validation_files.txt'?
I downloaded the NTURGB dataset but didn't see any txt.files.
Did you design these txt.files by yourself? Could you explain more details about this?
Thanks

**Comment by vadeli** [comment]
Same issue. Have you figured it out?

**Comment by kstudy123** [comment]
Hello, have you solved this problem and how did you solve it? Thank you
