### ISSUE TITLE
can not run your code

### ISSUE THREAD

**Issue by Bobby-youngking** [idiap/potr#4]
if 'all' in params['action']:
    params['action_subset'] = _ALL_ACTIONS
this line of code is not right

**Comment by legan78** [comment]
Hi! thanks for your comment. There is an argument missing `--action=all`. We have updated the instructions to run training.

**Comment by Bobby-youngking** [comment]
hi, i didn't find the action_def.json

**Comment by kb077** [comment]
> hi, i didn't find the action_def.json

Same issue. can not find the action_defs.json file. Did you find yet?
