### ISSUE TITLE
question about H36MDataset_v2.py

### ISSUE THREAD

**Issue by HongGu-Jeong** [idiap/potr#7]
hello,

I have a few questions about data processing .

I read your paper, 
"Pose Transformers: Human Motion Prediction with Non-Autoregressive Transformers ".

then I found a different part of what I understood in the published code .

1)
I found "self._params['include_last_obs"]" in H36MDataset_v2.py in data folder

And it is not written on Training instruction in readme.

so it is false and make the number of encoder_input sequence to 49 that I read 50 in your paper.

2)
And The same goes for class tokens. it's default value is false, and did not used in prediction.

I understood it to be used.

3)
The "self._params['pad_decoder_inputs']" in H36MDataset_v2.py is True,
because it is written in Training instruction in readme.

I read  "We select the last element of the sequence XT, as the query pose and fill the query sequence with this entry" in paper_3.2 Pose Transformer.

However, in the published code. 

decoder_inputs[0:1, :] is selected as query. and it is not same a last one of encoder_inputs.

They have one frame difference.

Thank you for your time to read it

**Comment by legan78** [comment]
Hi. Thanks for your message. 1) Removing one element from the input allows to use it as query. 2) When pad_decoder_inputs is set to True decoder_inputs is filled with the same pose corresponding to X_T. Then taking any element from decoder_inputs matches to X_T
